### ISSUE TITLE
Uncaught TypeError: HTMLMediaElement.currentTime setter: Value being assigned is not a finite floating-point value.

### ISSUE THREAD

**Issue by bobaaaaa** [stroeer/stroeer-videoplayer-default-ui#35]
<img width="976" alt="Bildschirmfoto 2023-01-10 um 21 40 49" src="https://user-images.githubusercontent.com/733158/211657620-7edf6c6e-9982-4aa0-9d5d-11b571f7c3fd.png">

https://github.com/stroeer/stroeer-videoplayer-default-ui/blob/dcda8197f4cee8317a7c58924587a2562bb91a28/src/UI.ts#L805

**Comment by walialu** [comment]
Danke fuers melden, habs in unser Sammelbecken ueberfuehrt und mache hier zu, weils dann in dem Monorepo weitergeht :) 

Wir sind zwar noch nicht fertig mit dem Monorepo, sammeln dort aber schonmal die Issues und prozessieren von dort weiter.
