### ISSUE TITLE
Please remove all console.log statements

### ISSUE THREAD

**Issue by bobaaaaa** [stroeer/stroeer-videoplayer-default-ui#8]
https://github.com/stroeer/stroeer-videoplayer-default-ui/blob/619ca4cd4d1b2b5652b743f4c578067361b12628/src/UI.ts#L142

Maybe this helps: https://www.npmjs.com/package/@rollup/plugin-strip

## Why

When rendering the videoplayer server side (via tests) these logs are just noise.

**Comment by walialu** [comment]
@ennoStroeer, du 🚀, kannst du dich da nach deinem Urlaub 🏝️ drum kümmern, bitte ❤️?

**Comment by ennoStroeer** [comment]
Some call it noise, some call it Punk-Music :grin: 
I wil remove them.

**Comment by walialu** [comment]
Should be fixed with https://github.com/stroeer/stroeer-videoplayer-default-ui/releases/tag/v0.0.7
